import UFPFormalization.SpecCategory
import Mathlib.CategoryTheory.Category.Basic
import Mathlib.Data.Matrix.Basic

open CategoryTheory Matrix

namespace UFPFormalization

/-!
# Higher Spec₂ 2-Category (D28.4 / Phase 29)

2-category lifting of Spec (deepening notes §A.2):

  - Objects: spectral objects (SpecObj)
  - 1-morphisms: SpecHom (intertwining operators)
  - 2-morphisms: homotopies between intertwining operators

A 2-morphism β : P ⇒ Q between SpecHom P,Q : X → Y is represented
by a homotopy matrix H satisfying Q - P = [A_X, H] (infinitesimal form).
-/

universe u

/--
A 2-morphism in Spec₂: β : P ⇒ Q where P,Q : X → Y are SpecHom.

In the finite prototype, a 2-morphism is a homotopy matrix H such that
the difference Q - P is generated by commutation with A_X.
-/
structure SpecTwoMorphism {X Y : SpecObj} (P Q : X ⟶ Y) where
  /-- The homotopy matrix encoding the 2-morphism. -/
  homotopy : Matrix (Fin (X.dim)) (Fin (Y.dim)) ℂ
  /-- Homotopy condition: Q.matrix - P.matrix = X.A * homotopy - homotopy * Y.A -/
  condition : Q.matrix - P.matrix = X.A * homotopy - homotopy * Y.A

/--
Vertical composition of Spec 2-morphisms: β ∘_v α : P ⇒ R
where α : P ⇒ Q and β : Q ⇒ R.

Defined by addition of homotopy matrices.
-/
def specVertComp {X Y : SpecObj} {P Q R : X ⟶ Y}
    (α : SpecTwoMorphism P Q) (β : SpecTwoMorphism Q R) : SpecTwoMorphism P R :=
  { homotopy := α.homotopy + β.homotopy
    condition := by
      calc
        R.matrix - P.matrix = (R.matrix - Q.matrix) + (Q.matrix - P.matrix) := by ring
        _ = (Y.A * β.homotopy - β.homotopy * X.A) + (Y.A * α.homotopy - α.homotopy * X.A) := by
          rw [β.condition, α.condition]
        _ = Y.A * (α.homotopy + β.homotopy) - (α.homotopy + β.homotopy) * X.A := by ring
        _ = Y.A * (α.homotopy + β.homotopy) - (α.homotopy + β.homotopy) * X.A := rfl
  }

/--
Horizontal composition of Spec 2-morphisms: α ∘_h α' : P∘P' ⇒ Q∘Q'
where α : P ⇒ Q : X → Y and α' : P' ⇒ Q' : Y → Z.

Defined by: H_comp = H ⊗ P' + Q ⊗ H'
-/
def specHorizComp {X Y Z : SpecObj} {P Q : X ⟶ Y} {P' Q' : Y ⟶ Z}
    (α : SpecTwoMorphism P Q) (α' : SpecTwoMorphism P' Q') :
    SpecTwoMorphism (P ≫ P') (Q ≫ Q') :=
  { homotopy := α.homotopy * P'.matrix + Q.matrix * α'.homotopy
    condition := by
      calc
        (Q ≫ Q').matrix - (P ≫ P').matrix
            = (Q.matrix * Q'.matrix) - (P.matrix * P'.matrix) := rfl
        _ = (Q.matrix - P.matrix) * Q'.matrix + P.matrix * (Q'.matrix - P'.matrix) := by ring
        _ = (Y.A * α.homotopy - α.homotopy * X.A) * Q'.matrix
            + P.matrix * (Z.A * α'.homotopy - α'.homotopy * Y.A) := by
          rw [α.condition, α'.condition]
        _ = X.A * (α.homotopy * P'.matrix + Q.matrix * α'.homotopy)
            - (α.homotopy * P'.matrix + Q.matrix * α'.homotopy) * Z.A := by ring
        _ = X.A * homotopy - homotopy * Z.A := rfl
  }

/--
The identity 2-morphism id_P : P ⇒ P.
-/
def specIdTwoMorphism {X Y : SpecObj} (P : X ⟶ Y) : SpecTwoMorphism P P :=
  { homotopy := 0
    condition := by
      simp }

/--
Vertical composition associativity.
-/
theorem specVertComp_assoc {X Y : SpecObj} {P Q R S : X ⟶ Y}
    (α : SpecTwoMorphism P Q) (β : SpecTwoMorphism Q R) (γ : SpecTwoMorphism R S) :
    specVertComp (specVertComp α β) γ = specVertComp α (specVertComp β γ) := by
  ext
  simp [specVertComp, add_assoc]

/--
Exchange law for Spec₂ 2-morphisms.
-/
theorem specExchangeLaw {X Y Z : SpecObj}
    {P Q : X ⟶ Y} {P' Q' : Y ⟶ Z}
    (α : SpecTwoMorphism P Q) (β : SpecTwoMorphism P Q)
    (α' : SpecTwoMorphism P' Q') (β' : SpecTwoMorphism P' Q') :
    specHorizComp (specVertComp α β) (specVertComp α' β') =
    specVertComp (specHorizComp α α') (specHorizComp β β') := by
  ext
  simp [specVertComp, specHorizComp, add_comm, add_left_comm, add_assoc]

end UFPFormalization
