import UFPFormalization.SpecCategory
import UFPFormalization.HigherSpecCategory
import UFPFormalization.AInfinityAlgebra
import Mathlib.Data.Matrix.Basic
import Mathlib.LinearAlgebra.Matrix.Trace

open Matrix

namespace UFPFormalization

/-!
# ∞-Category Tangent Space and Spectral Flow (Phase 31.1)

In the ∞-category Spec_∞, the spectral flow equation becomes a tangent vector
field on the morphism space:

    dA/dt = [G, A] ∈ T_A Spec_∞

Force generators A_{F,i} are Killing vector fields on Spec_∞, and the
spectral flow equation is the Lie derivative along these fields.

This module builds on `AInfinityAlgebra.lean`: the operation m_1 = ad_G is
exactly the tangent vector generating the spectral flow.  The finite
prototype defines:
  - The tangent space at A: T_A Spec_∞ = { [G,A] | G ∈ End(H) }
  - The Killing condition: Tr([A_F, A]·B) + Tr(A·[A_F, B]) = 0
  - The unified spectral flow equation as a sum of Killing fields.
-/

universe u

/--
Tangent vector in Spec_∞ at point A, generated by G.

In the ∞-category interpretation, this represents the spectral flow:
    dA/dt = [G, A] ∈ T_A Spec_∞
-/
structure TangentVector (n : ℕ) (A : Matrix (Fin n) (Fin n) ℂ) where
  /-- The generator of the spectral flow. -/
  generator : Matrix (Fin n) (Fin n) ℂ

/-- The tangent vector is [G, A] = G*A - A*G. -/
def TangentVector.flow {n : ℕ} {A : Matrix (Fin n) (Fin n) ℂ} (v : TangentVector n A) :
    Matrix (Fin n) (Fin n) ℂ :=
  ad v.generator A

/--
Killing vector field on Spec_∞.

A vector field X is Killing if the Lie derivative of the canonical metric
    g(X,Y) = Tr(X·Y)
along X vanishes:
    L_X g = 0
This is equivalent to: Tr([A_F, A]·B) + Tr(A·[A_F, B]) = 0.
-/
structure KillingField (n : ℕ) where
  /-- The force generator A_F. -/
  generator : Matrix (Fin n) (Fin n) ℂ
  /-- The flow it generates at point A. -/
  flowAt (A : Matrix (Fin n) (Fin n) ℂ) : Matrix (Fin n) (Fin n) ℂ :=
    ad generator A
  /-- Killing condition: the flow preserves the trace metric. -/
  killingCondition (A B : Matrix (Fin n) (Fin n) ℂ) : Prop :=
    Matrix.trace (flowAt A * B) + Matrix.trace (A * flowAt B) = 0

/--
The four force generators as Killing fields on Spec_∞:
  - A_GR: gravity
  - A_EM: electromagnetism
  - A_SU(3): strong force
  - A_SU(2): weak force
-/
structure ForceGenerators (n : ℕ) where
  gravity : KillingField n
  em : KillingField n
  strong : KillingField n
  weak : KillingField n

/--
The unified spectral flow equation as a sum of Killing fields:

    dA/dt = Σ_i g_i · [A_{F,i}, A]
          = Σ_i g_i · Lie_{A_{F,i}} A

where Lie_{A_F} A = [A_F, A] is the Lie derivative.
-/
def unifiedSpectralFlow (n : ℕ) (forces : ForceGenerators n)
    (couplings : Fin 4 → ℂ) (A : Matrix (Fin n) (Fin n) ℂ) :
    Matrix (Fin n) (Fin n) ℂ :=
  couplings 0 • forces.gravity.flowAt A +
  couplings 1 • forces.em.flowAt A +
  couplings 2 • forces.strong.flowAt A +
  couplings 3 • forces.weak.flowAt A

/--
Theorem: The spectral flow equation dA/dt = [G,A] is equivalent to
the Lie derivative along the Killing field generated by G on Spec_∞.

Proof: [G,A] = L_G A by definition of the Lie derivative on Spec_∞.
-/
theorem spectral_flow_as_lie_derivative (n : ℕ)
    (G A : Matrix (Fin n) (Fin n) ℂ) :
    G * A - A * G = ad G A := by
  rfl

/--
Theorem: Every tangent vector in Spec_∞ arises from the L∞ operation m_1.

This connects the geometric tangent-space picture with the algebraic
A∞-algebra foundation in `AInfinityAlgebra.lean`.
-/
theorem tangent_vector_is_m1 (n : ℕ) (A : Matrix (Fin n) (Fin n) ℂ)
    (v : TangentVector n A) :
    v.flow = m1 v.generator A := by
  simp [TangentVector.flow, m1, mN, ad]

end UFPFormalization
