-- ============================================================
-- UFPF → MUFPF 更名通知
-- ============================================================
-- 本文件属于 Universal Fixed Point Framework (UFPF)。
-- 该框架已计划更名为 Meta-Universal Fixed-Point Functorial Framework (MUFPF)。
-- 更名计划详见：roadmap/mu_renaming_plan.md
--
-- 原因：UFPF 缩写与 IEEE 生物图像识别框架冲突，影响学术检索。
-- 新名称 MUFPF 具有全球唯一性，且更好地体现框架的元数学特性。
--
-- 本文件中 UFPF 相关引用数量：4
-- 更名将在计划确认后统一执行，当前代码不做修改。
-- ============================================================

import UFPFormalization.SpCategory
import UFPFormalization.AInfinityAlgebra
import Mathlib.CategoryTheory.Category.Basic
import Mathlib.Data.Matrix.Basic

open CategoryTheory Matrix

namespace UFPFormalization

/-! 
# Spec_∞ : ∞-Category of Spectral Objects (Phase 31.1)

Spec_∞ is the ∞-category whose objects are spectral objects (SpObj) and whose
higher morphisms are homotopies between intertwining operators, generated by the
L∞-algebra structure m_n = ad_G^n on the space of operators.

In this finite prototype an ∞-morphism records an intertwining matrix P and a
spectral-flow generator G.  Higher components are generated by the L∞ operation
ad_G, but we keep the structure minimal to ensure type-correctness and avoid
heavy matrix-sum proofs.
-/

universe u

/-- An ∞-morphism between spectral objects X and Y. -/
@[ext]
structure SpecInfMorphism (X Y : SpObj) where
  /-- Underlying 1-morphism matrix. -/
  P : Matrix (Fin X.n) (Fin Y.n) ℂ
  /-- Spectral flow generator. -/
  generator : Matrix (Fin X.n) (Fin Y.n) ℂ
  /-- Base intertwining condition: P * Y.A = X.A * P. -/
  intertwine : P * Y.A = X.A * P

/-- The underlying SpHom of an ∞-morphism. -/
def SpecInfMorphism.toSpHom {X Y : SpObj} (α : SpecInfMorphism X Y) : X ⟶ Y :=
  { P := α.P
    intertwine := α.intertwine }

/-- Vertical composition of Spec_∞ morphisms (matrix multiplication). -/
def specInfVertComp {X Y Z : SpObj} (α : SpecInfMorphism X Y) (β : SpecInfMorphism Y Z) :
    SpecInfMorphism X Z :=
  { P := α.P * β.P
    generator := α.generator * β.generator
    intertwine := by
      rw [Matrix.mul_assoc]
      rw [β.intertwine]
      rw [← Matrix.mul_assoc]
      rw [α.intertwine]
      rw [Matrix.mul_assoc] }

/-- Identity Spec_∞ morphism. -/
def specInfId (X : SpObj) : SpecInfMorphism X X :=
  { P := 1
    generator := 0
    intertwine := by simp }

/-- Spec_∞ has objects SpObj and ∞-morphisms SpecInfMorphism. -/
def SpecInfinity : Type _ := SpObj

end UFPFormalization
