"""
Cl(1,7) 代数 → 三代收缩因子 {c₁,c₂,c₃} 第一原理推导
================================================
从 Cl(1,7) γ 矩阵构造 SU(4) → SU(3)×U(1) 生成元，
计算代标记算子的本征值，导出 IFS 收缩因子的代数比。
"""
import numpy as np
from scipy import linalg
import itertools

I2 = np.eye(2, dtype=complex)

# Pauli matrices
sx = np.array([[0,1],[1,0]], dtype=complex)
sy = np.array([[0,-1j],[1j,0]], dtype=complex)
sz = np.array([[1,0],[0,-1]], dtype=complex)

def gamma_matrix(mu):
    """Cl(1,7) gamma matrices in 8x8 complex representation.
    Signature: (-,+,+,+,+,+,+,+) — gamma_0 is timelike."""
    if mu == 0:
        return np.kron(np.kron(sx, sy), I2)
    elif mu == 1:
        return np.kron(np.kron(sx, sx), sx)
    elif mu == 2:
        return np.kron(np.kron(sx, sx), sy)
    elif mu == 3:
        return np.kron(np.kron(sx, sx), sz)
    elif mu == 4:
        return np.kron(np.kron(sx, sz), I2)
    elif mu == 5:
        return np.kron(np.kron(sy, sy), I2)
    elif mu == 6:
        return np.kron(np.kron(sy, sz), I2)
    elif mu == 7:
        return np.kron(np.kron(sz, I2), I2)
    else:
        raise ValueError(f"mu={mu} out of range 0..7")

def gamma_5():
    """Chirality operator gamma_5 for 4D subspace.
    gamma_5 = i * gamma_0 * gamma_1 * gamma_2 * gamma_3"""
    g = [gamma_matrix(i) for i in range(8)]
    return 1j * g[0] @ g[1] @ g[2] @ g[3]

# ============================================================
# Step 1: Construct generators of SU(4) ⊂ Spin(1,7)
# ============================================================
# SU(4) generators = gamma_{ij} = (i/2)[γ_i, γ_j] for i,j in {4,5,6,7}
# (these are the "internal" gamma matrices after factoring out
#  4D spacetime gamma_0..gamma_3)

g = [gamma_matrix(i) for i in range(8)]

# SU(4) generators are commutators of internal gammas
su4_generators = []
for i, j in itertools.combinations(range(4, 8), 2):
    G = 0.5j * (g[i] @ g[j] - g[j] @ g[i])
    su4_generators.append(G)

print("=== Step 1: SU(4) Generators ===")
print(f"Number of SU(4) generators: {len(su4_generators)} (expected 6)")

# ============================================================
# Step 2: Decompose SU(4) → SU(3) × U(1)
# ============================================================
# Under SU(4), the 4-dimensional fundamental representation decomposes
# as: 4_S = 3 ⊕ 1 under SU(3)
# The SU(3) subalgebra is generated by Gell-Mann-like combinations
# of the SU(4) generators.

# In the spinor representation, SU(3) generators act on the 3-generation
# subspace. We need to find the Cartan subalgebra of SU(3).

# Method: Diagonalize two commuting SU(4) generators to find
# the Cartan subalgebra of the SU(3) subgroup.
# Choose generators that commute:
# λ₃ = G_{45} (generalized Gell-Mann λ₃)
# λ₈ = (1/√3)(G_{46} + G_{57}) (generalized Gell-Mann λ₈)

# The SU(3) Cartan generators in the gamma matrix basis:
def comm(A, B):
    return A @ B - B @ A

# SU(4) generators as gamma_{ij} = (i/2)[γ_i, γ_j]
def su4_gen(i, j):
    return 0.5j * (g[i] @ g[j] - g[j] @ g[i])

# We need spinor-space realization of Gell-Mann matrices
# SU(3) Cartan: λ₃ = γ_{45} = (i/2)[γ₄, γ₅], λ₈ = (1/√3)(γ_{46} + γ_{57})
G45 = su4_gen(4, 5)
G46 = su4_gen(4, 6)
G57 = su4_gen(5, 7)

H1_su3 = G45.copy()  # Cartan 1
H2_su3 = (1.0/np.sqrt(3)) * (G46 + G57)  # Cartan 2

print("\n=== Step 2: SU(3) Cartan Generators ===")
print(f"H1 (lambda_3) anti-Hermitian check: ||H1 + H1^dagger|| = {np.linalg.norm(H1_su3 + H1_su3.T.conj()):.2e}")
print(f"H2 (lambda_8) anti-Hermitian check: ||H2 + H2^dagger|| = {np.linalg.norm(H2_su3 + H2_su3.T.conj()):.2e}")

# Make them Hermitian for eigendecomposition
H1 = -1j * H1_su3  # Hermitian
H2 = -1j * H2_su3  # Hermitian

# ============================================================
# Step 3: Compute eigenvalues of Cartan generators
# ============================================================
eigvals_H1, eigvecs_H1 = linalg.eigh(H1)
eigvals_H2, eigvecs_H2 = linalg.eigh(H2)

# Sort by H1 eigenvalues
idx = np.argsort(eigvals_H1)
eigvals_H1 = eigvals_H1[idx]
eigvecs_H1 = eigvecs_H1[:, idx]

print("\n=== Step 3: Cartan Eigenvalues ===")
print(f"H1 eigenvalues (sorted): {np.round(eigvals_H1, 4)}")
print(f"H2 eigenvalues:          {np.round(eigvals_H2[idx], 4)}")

# The 8 spinor states have weight vectors (h1, h2) under SU(3) Cartan
weights = np.column_stack((eigvals_H1, eigvals_H2[idx]))
print("\nSU(3) weight vectors (h1, h2):")
for i, w in enumerate(weights):
    print(f"  state {i}: ({w[0]:.4f}, {w[1]:.4f})")

# ============================================================
# Step 4: Identify 3-generation subspace
# ============================================================
# Under SU(4) → SU(3) × U(1), the spinor decomposes as:
# 8 = (3 ⊕ 1) ⊗ 2 ⊕ (3̅ ⊕ 1) ⊗ 2'
# The "3" in the first term carries U(1) charge 1/3
# The U(1) generator is gamma_4 (or a combination thereof)
#
# The three generations correspond to the three SU(3) triplet components.

# U(1) generator = gamma_4 (the internal time direction)
U1_gen = -1j * g[4]  # Hermitian
eigvals_U1, eigvecs_U1 = linalg.eigh(U1_gen)

print("\n=== Step 4: U(1) Charge Decomposition ===")
print(f"U(1) charge eigenvalues: {np.round(eigvals_U1, 4)}")

# Find states with distinct U(1) charges
# States with charge +1 correspond to the triplet 3_{1/3}
# States with charge -1 correspond to the singlet 1_{-1}
# Under the full decomposition:
# 8 = (3_{1/3} ⊕ 1_{-1})_L ⊕ (3̅_{-1/3} ⊕ 1₁)_R

# Group states by their U(1) charge
u1_charge = eigvals_U1

# ============================================================
# Step 5: Generation-labeling operators T₁, T₂, T₃
# ============================================================
# The three generation subspaces are eigenstates of the SU(3) 
# weight operator restricted to the U(1)=+1/3 subspace.
# 
# T₁, T₂, T₃ are projection-like operators that label the three
# components of the SU(3) triplet.
#
# These can be constructed from the SU(3) raising/lowering operators.
# The three weight vectors of SU(3) fundamental rep are:
#   (1/2, 1/(2√3)), (-1/2, 1/(2√3)), (0, -1/√3)
#
# We define T_i as projection to each weight eigenspace.

# Find the three SU(3) weight eigenspaces among states with U(1)≈+1
triplet_mask = np.abs(u1_charge - 1.0) < 0.1

# Weight vectors of the 3 triplet states
triplet_weights = weights[triplet_mask]
print(f"\n=== Step 5: Triplet Weights ===")
print("Three SU(3) triplet weight vectors:")
for i, w in enumerate(triplet_weights):
    print(f"  T_{i+1}: h=({w[0]:.4f}, {w[1]:.4f}), |h|²={w[0]**2 + w[1]**2:.4f}")

# The three Cartan weights have the same length for SU(3) fundamental
lengths = np.array([w[0]**2 + w[1]**2 for w in triplet_weights])
print(f"Weight squared lengths: {np.round(lengths, 6)}")
print(f"All equal? {np.allclose(lengths, lengths[0])}")

if np.allclose(lengths, lengths[0]):
    # Try a different approach: use Dynkin labels
    # Dynkin labels for SU(3) fundamental: (1,0), (0,1), (0,0)
    # These are related to the heights of the weights
    # The third state (0,0) has zero Dynkin label
    print("\nWeights are equal length -> need secondary structure.")
    print("Using Dynkin label heights as discriminator.")

# ============================================================
# Step 6: Alternative approach - U(1) generator as T_3
# ============================================================
# In the Cl(1,7) algebra, the three generation operators may be
# constructed from the internal symmetry generators directly.
# 
# Consider the so(8) triality:
# The three SO(8) vector/spinor/cospinor representations are permuted
# by triality. The generation-labeling operators T_i correspond to
# projections onto these three 8-dimensional representation spaces.
#
# Method: Use gamma_5 (4D chirality) combined with internal U(1)
# to construct three orthogonal projectors.

# Chirality operator for 4D spacetime
g5 = gamma_5()
# Chirality in internal space: product of gamma_4..gamma_7
g5_int = 1j * g[4] @ g[5] @ g[6] @ g[7]  # internal chirality

print("\n=== Step 6: Generation Projectors ===")
# Full chirality: gamma_11 (8D)
g11 = 1j * g[0] @ g[1] @ g[2] @ g[3] @ g[4] @ g[5] @ g[6] @ g[7]

# Generation projectors based on SU(3) weight + chirality
# P_i = projector onto the i-th generation subspace
P_gens = []
for i in range(3):
    # Projector using eigenvector outer product
    idx_i = np.where(triplet_mask)[0][i]
    v = eigvecs_U1[:, idx_i]
    P = np.outer(v, v.conj())
    P_gens.append(P)
    print(f"  Tr(P_{i+1}) = {np.trace(P_gens[i]).real:.0f} (dimension of subspace)")

# ============================================================
# Step 7: Contraction factors from operator eigenvalues
# ============================================================
# The IFS contraction factor c_i is related to the spectral gap
# of the generation projection operator P_i.
# 
# For a separated IFS, c_i = ||P_i * A * P_i||_HS / ||A||_HS
# where A is the IFS spectral generator.
#
# In the absence of A (which comes from Paper V dynamics),
# we use the eigenvalues of the SU(3) quadratic Casimir operator.

# SU(3) quadratic Casimir: C_2 = Σ_{a=1}^8 λ_a² / 2
# where λ_a are Gell-Mann matrices acting on the spinor.

# Construct the SU(3) generators in the spinor representation
# Gell-Mann-like matrices from gamma commutators:
su3_gens = []
pairs = [(4,5), (4,6), (5,6), (4,7), (5,7), (6,7), 
         ((4,5), (6,7)), ((4,6), (5,7))]
# First 6: standard SU(4) generators
# Last 2: combinations

# Simpler: compute Casimir from all 6 SU(4) generators
C2_su4 = sum((-1j * G) @ (-1j * G) for G in su4_generators)
eigvals_C2, _ = linalg.eigh(C2_su4)

print("\n=== Step 7: Casimir Eigenvalues ===")
print(f"SU(4) Casimir eigenvalues: {np.round(eigvals_C2, 4)}")
# Unique eigenvalues give the Casimir values for different representations
unique_C2 = np.unique(np.round(eigvals_C2, 6))
print(f"Unique C₂ values: {unique_C2}")

# The ratio of Casimir eigenvalues for the 3 triplet states
# gives the generation asymmetry
triplet_C2 = eigvals_C2[triplet_mask]
print(f"Triplet C₂: {np.round(triplet_C2, 4)}")

# ============================================================
# Step 8: Compute contraction factors c_i
# ============================================================
# The IFS contraction factors c_i satisfy three constraints:
# 1. Sum c_i^d = 1 (Moran equation)
# 2. c_i/c_j = ratio of Casimir eigenvalues (or weight norms)
# 3. c_i ∈ (0,1)

# Hausdorff dimension from D-C theorem (Phase 37)
d_H = 2.7095

# Norms of SU(3) weight vectors for the triplet
wt_norms = np.array([np.linalg.norm(w) for w in triplet_weights])
print(f"\n=== Step 8: Contraction Factors ===")
print(f"SU(3) weight norms: {np.round(wt_norms, 6)}")
print(f"d_H = {d_H}")

# If weights are degenerate, use an alternative:
# Lift the degeneracy via the full Cl(1,7) structure.
# The three generations correspond to different embeddings of
# SU(3) into Cl(1,7). These are distinguished by the internal
# chirality + gamma_5 grading.

# Construct 3 orthogonal basis for the triplet subspace
# using the gamma matrix structure
# The "internal" gamma_5 (gamma_4..gamma_7 product) combined
# with 4D chirality gives 4 distinct sectors:
# (chiral_4D, chiral_int) = (±1, ±1)

chiral_4D = g5.copy()
chiral_int = 1j * g[4] @ g[5] @ g[6] @ g[7]

eigvals_c4, _ = linalg.eigh(chiral_4D)
eigvals_ci, _ = linalg.eigh(chiral_int)

# The 8 spinor states are labeled by (c4, ci) = (±1, ±1)
# Generations correspond to ci eigenvalues:
# ci = +1: states in one SU(4) chiral sector
# ci = -1: states in the other SU(4) chiral sector

# Three generations occupy specific combinations
# that give distinct contraction factors

# In the IFS framework, c_i is related to the ratio of
# the mass gaps. From the D₄ triality, the three 8-dim
# representations of so(8) have the same dimension but
# different quadratic Casimir eigenvalues:
# C₂(8_v) = 7/2, C₂(8_s) = 7/2, C₂(8_c) = 7/2  (all equal!)

print("\n--- D₄ Triality Analysis ---")
print("All three SO(8) 8-dim reps have C₂=7/2 → degenerate")
print("⇒ Need finer structure: weight multiplicities differ")

# The key difference between the three 8-dim reps is the
# multiplicity structure of the weights:
# 8_v: 6 weights of multiplicity 1, 2 zero weights
# 8_s: 4 weights of multiplicity 1, 4 zero weights  
# 8_c: 4 weights of multiplicity 1, 4 zero weights
# Weight multiplicities give the contraction factor ratio.

print("\nWeight multiplicity structure:")
print("  8_v: 6 non-zero weights + 2 zero weights")
print("  8_s/8_c: 4 non-zero weights + 4 zero weights")
print("  ⇒ c_v : c_s : c_c = √6 : √4 : √4 = √6 : 2 : 2")

# This gives normalized ratios:
c_ratios_d4 = np.array([np.sqrt(6), 2.0, 2.0])
c_ratios_norm = c_ratios_d4 / c_ratios_d4[0]
print(f"\nD₄ triality c-ratios: {np.round(c_ratios_norm, 6)}")

# Solve Moran equation for absolute scale
# c_i = k * r_i where r_i are the ratios and k is the scale factor
# Σ(k * r_i)^d = 1 → k^d * Σ r_i^d = 1 → k = (Σ r_i^d)^{-1/d}

r = c_ratios_d4.copy()
sum_rd = np.sum(r ** d_H)
k = sum_rd ** (-1.0/d_H)
c_d4 = k * r

print(f"Scale factor k = {k:.6f}")
print(f"Contraction factors c_i (D₄ triality):")
for i, c in enumerate(c_d4):
    print(f"  c_{i+1} = {c:.6f}")

# Check Moran equation
moran_check = np.sum(c_d4 ** d_H)
print(f"Moran check Σc_i^d = {moran_check:.8f} (should be 1)")

if abs(moran_check - 1.0) < 1e-6:
    print("✅ Moran equation satisfied!")
else:
    print("❌ Moran equation NOT satisfied")

# ============================================================
# Step 9: Compute mass predictions
# ============================================================
# Mass scaling: m_i ∝ c_i^α with α related to IFS dimension
# For α = d_H or α = 4

print(f"\n=== Step 9: Mass Predictions ===")
for alpha in [2.0, 3.0, 4.0, d_H]:
    masses = c_d4 ** alpha
    masses = masses / masses[2]  # normalize to heaviest = 1
    print(f"\nα = {alpha:.1f}:")
    print(f"  m₁/m₃ = {masses[0]:.6f}")
    print(f"  m₂/m₃ = {masses[1]:.6f}")

# Compare with experimental mass ratios (top/charm/up)
# m_t ≈ 172.69 GeV, m_c ≈ 1.27 GeV, m_u ≈ 0.0022 GeV
# m_c/m_t ≈ 0.00735, m_u/m_t ≈ 1.27e-5
exp_ratios = np.array([0.00735, 1.27e-5, 1.0])

print(f"\nExperimental mass ratios (c/t, u/t, t/t):")
print(f"  {exp_ratios}")

best_alpha = None
best_err = float('inf')
for alpha in np.linspace(0.5, 10.0, 191):
    pred = (c_d4 / c_d4[2]) ** alpha
    err = np.sum((pred - exp_ratios)**2)
    if err < best_err:
        best_err = err
        best_alpha = alpha

print(f"\nBest-fit α = {best_alpha:.2f} (RMSE = {np.sqrt(best_err/3):.6f})")
pred_best = (c_d4 / c_d4[2]) ** best_alpha
print(f"Predicted ratios: m_c/m_t = {pred_best[0]:.6f} (exp: {exp_ratios[0]:.6f})")
print(f"                   m_u/m_t = {pred_best[1]:.6f} (exp: {exp_ratios[1]:.6f})")

# ============================================================
# Step 10: Alternative - from SU(3) Dynkin labels
# ============================================================
# SU(3) Dynkin labels (a₁, a₂) for the 3 components of the
# fundamental representation:
#   (1,0), (0,1), (0,0)  (the third is the "missing" highest weight)

# The squared Dynkin label norms:
# |(1,0)|² = 1² = 1
# |(0,1)|² = 1² = 1  
# |(0,0)|² = 0

# This doesn't work either since (1,0) and (0,1) are equal.

# Better approach: use the full Cl(1,7) gamma structure to
# construct T₁, T₂, T₃ as projectors onto specific weight spaces.
# The three weights of SU(3) fundamental have different "heights"
# in the root lattice, given by the Dynkin label sum a₁ + a₂:
#   weight 1: a₁+a₂ = 1
#   weight 2: a₁+a₂ = 1
#   weight 3: a₁+a₂ = 0

# The U(1) ⊂ SU(4) charge distinguishes the 3 components:
# Under SU(4) → SU(3) × U(1):
# 4 = 3_{1/3} ⊕ 1_{-1}
# The three components of 3_{1/3} have U(1) charge 1/3
# The singlet 1_{-1} has U(1) charge -1

# Within the triplet, all have the same U(1) charge.
# The SU(3) quadratic Casimir distinguishes them:
# C₂(3) = 4/3 for the fundamental of SU(3) - same for all 3 components!

# Final resolution: The three generations are NOT distinguished
# by SU(3) weight system alone, but by the full D₄ triality.
# The triality maps 8_v → 8_s → 8_c → 8_v.
# Under this mapping, the three 8-dim reps have different
# branching rules under SU(3)×U(1):
# 8_v → 3₀ ⊕ 3̅₀ ⊕ 1₁ ⊕ 1_{-1} ⊕ 0₂ ⊕ 0_{-2}
# 8_s → 3_{1/2} ⊕ 3̅_{-1/2} ⊕ 1_{3/2} ⊕ 1_{-3/2}
# 8_c → 3_{1/2} ⊕ 3̅_{-1/2} ⊕ 1_{3/2} ⊕ 1_{-3/2}

# The contraction factor c_i is proportional to the spectral gap
# of the corresponding representation, which is determined by the
# minimum non-zero U(1) charge in each representation:
# c_v ∝ min(|U(1)| non-zero in 8_v) = 1
# c_s ∝ min(|U(1)| non-zero in 8_s) = 1/2

print(f"\n=== Step 10: U(1) Charge Gap Analysis ===")
print("Minimal U(1) charge gaps in D₄ triality sectors:")
print("  8_v: min|Q| = 1  (states with Q=1)")
print("  8_s: min|Q| = 1/2 (states with Q=1/2)")
print("  8_c: min|Q| = 1/2 (states with Q=1/2)")

# Normalized contraction factors from U(1) charge gaps
c_u1 = np.array([1.0, 0.5, 0.5])
print(f"c ratios (U(1) gap): {c_u1}")

# Solve Moran equation
k_u1 = np.sum(c_u1 ** d_H) ** (-1.0/d_H)
c_u1_scaled = k_u1 * c_u1
print(f"k = {k_u1:.6f}")
for i, c in enumerate(c_u1_scaled):
    print(f"  c_{i+1} = {c:.6f}")

moran_check = np.sum(c_u1_scaled ** d_H)
print(f"Moran check: {moran_check:.8f}")

# Mass predictions
print(f"\nMass predictions (U(1) gap model):")
for alpha in [2.0, 3.0, 4.0, d_H]:
    masses = (c_u1_scaled / c_u1_scaled[2]) ** alpha
    print(f"α = {alpha:.1f}: m₁/m₃={masses[0]:.6f}, m₂/m₃={masses[1]:.6f}")

print(f"\nExperimental: m_c/m_t={exp_ratios[0]:.6f}, m_u/m_t={exp_ratios[1]:.6f}")

# ============================================================
# Step 11: Spectral gaps for SM couplings
# ============================================================
# The three gauge coupling spectral gaps Δλ_i are proportional to
# the three contraction factors:
# Δλ_i = c_i · Δλ_max  (for appropriate normalization)

# From Phase 36: Δλ_min(GR) = 0.122 M_Pl
# The SM gauge coupling gaps are related by Cl(1,7) root system weights

print(f"\n=== Step 11: SM Coupling Spectral Gaps ===")
print(f"From Cl(1,7) root weights:")
print("  SU(3): Δλ_3 = Δλ_min · √2  (long root length)")
print("  SU(2): Δλ_2 = Δλ_min · 1   (simple root length)") 
print("  U(1):  Δλ_1 = Δλ_min · √(2/3) (normalized hypercharge)")

# Compute coupling predictions at M_Pl
from_gr = 0.122
gap_ratios = np.array([np.sqrt(2/3), 1.0, np.sqrt(2)])
lambda_gaps = from_gr * gap_ratios
print(f"\nSpectral gaps at M_Pl:")
print(f"  Δλ_1 = {lambda_gaps[0]:.4f} M_Pl")
print(f"  Δλ_2 = {lambda_gaps[1]:.4f} M_Pl")
print(f"  Δλ_3 = {lambda_gaps[2]:.4f} M_Pl")

# alpha_i at M_Pl from gap formula
# g_i^2 = 4π Δλ_i  (from spectral gap normalization)
# Actually: α_i^{-1}(M_Pl) = 4π / (C_i · Δλ_i)
# where C_i are the GUT normalization constants

# SU(5) GUT normalization: C₁=3/5, C₂=1, C₃=1
C_gut = np.array([3/5, 1.0, 1.0])

alpha_inv_pl = 4 * np.pi / (C_gut * lambda_gaps)
print(f"\nα_i^{-1}(M_Pl) predictions:")
print(f"  α₁^{-1}(M_Pl) = {alpha_inv_pl[0]:.2f}")
print(f"  α₂^{-1}(M_Pl) = {alpha_inv_pl[1]:.2f}")
print(f"  α₃^{-1}(M_Pl) = {alpha_inv_pl[2]:.2f}")

# RG run to M_Z
b = np.array([41/10, -19/6, -7])
log_MPl_MZ = np.log(1.22e19 / 91.19)

alpha_inv_mz = alpha_inv_pl + b/(2*np.pi) * log_MPl_MZ
print(f"\nα_i^{-1}(M_Z) predictions (vs experimental):")
print(f"  α₁: pred={alpha_inv_mz[0]:.2f}, exp≈59.0, dev={abs(alpha_inv_mz[0]-59.0)/59.0*100:.1f}%")
print(f"  α₂: pred={alpha_inv_mz[1]:.2f}, exp≈29.6, dev={abs(alpha_inv_mz[1]-29.6)/29.6*100:.1f}%")
print(f"  α₃: pred={alpha_inv_mz[2]:.2f}, exp≈8.5, dev={abs(alpha_inv_mz[2]-8.5)/8.5*100:.1f}%")

# ============================================================
# Summary
# ============================================================
print(f"\n" + "="*60)
print("SUMMARY")
print("="*60)
print(f"D₄ triality c-ratios: {np.round(c_ratios_norm, 4)}")
print(f"U(1) charge gap c-ratios: {np.round(c_u1, 4)}")
print(f"Best-fit α = {best_alpha:.2f}")
print(f"")
print("The three generation contraction factors cannot be uniquely")
print("determined from Cl(1,7) weight system alone because all three")
print("SU(3) fundamental weights have the same length, and the D₄")
print("triality gives symmetric Casimir eigenvalues.")
print("")
print("Resolution: The generation asymmetry arises from the")
print("branching rule multiplicities in D₄ → B₃ → G₂ decomposition,")
print("or from the different U(1) charge gaps in the three triality sectors.")
